const TYPE_DEFINITION_GRAPHQL = 'GraphQL';
const TYPE_DEFINITION_TYPESCRIPT = 'TypeScript';
const CONFIG_KEY = 'gql'
const NESTJS_GRAPHQL_PLUGIN = '@nestjs/graphql';
const CONFIG_KEY_TYPE_DEFINITION = 'typeDefinition';
const CONFIG_KEY_EXPERIMENTAL_TRANSFORMER = 'experimentalTransformer';
const CONFIG_KEY_ENDPOINT = 'endpoint';
const CONFIG_KEY_SCHEMA_LOCATION = 'schemaLocation';

const constants = {
    TYPE_DEFINITION_GRAPHQL,
    TYPE_DEFINITION_TYPESCRIPT,
    CONFIG_KEY,
    CONFIG_KEY_TYPE_DEFINITION,
    CONFIG_KEY_EXPERIMENTAL_TRANSFORMER,
    CONFIG_KEY_ENDPOINT,
    CONFIG_KEY_SCHEMA_LOCATION,
    NESTJS_GRAPHQL_PLUGIN };

module.exports = constants;
